### PR TITLE
Allow to set custom cache key through options

### PR DESCRIPTION
**Pull request by matteodem**

### CODE REVIEW

**Comment by matteodem** [comment]
For some reason `withCache` calls on the same level generate the same cache keys. This option will allow to define a custom key.

**Comment by matteodem** [comment]
Need some guidance on how to fix the unit tests. Hope the config makes sense

**Comment by matteodem** [comment]
@Intellicode did you have time to look at this?

**Comment by Intellicode** [comment]
@matteodem Sorry, I completely missed it! Looks fine to me :)

update: Would you mind to fix the tests? Then I'll merge + release

**Comment by Intellicode** [comment]
You can fix the tests by providing a default for options, for example as part as the function arguments like this: `options = {}`

**Comment by matteodem** [comment]
@Intellicode thanks!

**Comment by Intellicode** [comment]
@matteodem you too, made a new release for you as well!

**Pull request merged**
